### PR TITLE
Started deleting variable if entity recursion exception is thrown on import

### LINKED ISSUE #388: Fixed error when importing a container: This variable cannot be deleted as it is used in other places
image

* Create a new container. 
* Go to versions
* Click on import
* Import below data

```
{"idcontainer":"lRjDHEmG","idsite":1,"context":"web","name":"test2","description":"","created_date":"2021-12-09 19:28:11","updated_date":"2021-12-09 19:28:11","created_date_pretty":"Dec 9, 2021 20:28:11","updated_date_pretty":"Dec 9, 2021 20:28:11","revision":0,"version":{"name":"","description":"","revision":0,"created_date":"2021-12-09 19:28:11","created_date_pretty":"Dec 9, 2021 20:28:11","updated_date":"2021-12-09 19:28:11","updated_date_pretty":"Dec 9, 2021 20:28:11"},"tags":[],"triggers":[],"variables":[{"idvariable":36,"type":"MatomoConfiguration","name":"Matomo Configuration","parameters":{"matomoUrl":"{{Matomo Configuration}}","idSite":"1","enableLinkTracking":true,"enableCrossDomainLinking":false,"enableDoNotTrack":false,"enableJSErrorTracking":false,"enableHeartBeatTimer":false,"trackAllContentImpressions":false,"trackVisibleContentImpressions":false,"disableCookies":false,"requireConsent":false,"requireCookieConsent":false,"setSecureCookie":false,"cookieDomain":"","cookiePath":"","cookieSameSite":"Lax","domains":[],"alwaysUseSendBeacon":false,"userId":"","customDimensions":[],"bundleTracker":true,"registerAsDefaultTracker":true,"jsEndpoint":"matomo.js","trackingEndpoint":"matomo.php"},"lookup_table":[],"default_value":"","created_date":"2021-12-09 19:28:53","updated_date":"2021-12-09 19:28:53","created_date_pretty":"Dec 9, 2021 20:28:53","updated_date_pretty":"Dec 9, 2021 20:28:53"}]}
```

What this import represents (refs https://github.com/matomo-org/tag-manager/pull/293 ):

> Eg create a MatomoConfiguration variable named "Matomo Configuration" and set Matomo URL to "https://matomo.org{{Matomo Configuration}}". 

The above one there is a variable that references itself which is causing this issue. Technically, this should not be happening anymore as we prevented a while ago this from happening and any newer container it shouldn't be possible to configure such a container. Unless someone configured the JSON themselves.

Maybe we could time box and look into this for 1 hour to see if we can fix this issue and make such imports happen and if not we might put it back in the backlog. If we can't solve it quick, maybe in import we could catch this error and then attach an extra message so it reads like `This variable cannot be deleted as it is used in other places. To remove this variable, first remove all places where this variable is used. It could be that a variable references itself within a variable.`. We wouldn't change the error message though in other places.

### PR DESCRIPTION
**Pull request by AltamashShaikh**
Started deleting variable if entity  recursion exception is thrown on import.
Fixes: #388 

### Description:

Please include a description of this change and which issue it fixes. If no issue exists yet please include context and what problem it solves.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Comment by tsteur** [comment]
@AltamashShaikh I see, the problem is when adding the variable there is a recursion. I thought it might happen when deleting or so. I think simply deleting the variable may not be expected as the user wouldn't be made aware of this problem that we skipped a variable and it could maybe even cause issues if other triggers or tags use this variable.

Instead we'd want to make sure that the user gets an accurate error message. In that case I would have expected we see the message like `'It seems an entity references itself or a recursion is caused in some other way. It may be related due to these entites: "'.implode(',', $entries). '". Please check if the entity references itself maybe or if a recursion might happen in another way.`. Do we know why we aren't seeing this?

This be the most important for now.

As a next step we would need to see if we can revert to the previously active draft as the import would then have worked partially I assume? This is out of scope for now unless it's super trivial. Let's mostly make sure that the correct error message is shown. We could then keep the issue open and eventually work on the other part.

File: API/Import.php [hunk 1]
```diff
@@ -133,16 +134,20 @@ public function importContainerVersion($exportedContainerVersion, $idSite, $idCo
...
+                    'idContainer' => $idContainer,
+                    'idContainerVersion' => $idContainerVersion,
+                    'type' => $variable['type'],
+                    'name' => $variable['name'],
+                    'parameters' => $variable['parameters'],
+                    'defaultValue' => $variable['default_value'],
+                    'lookupTable' => $variable['lookup_table'],
+                ));
+            } catch (EntityRecursionException $e){
+                throw new \Exception(Piwik::translate('TagManager_EntityRecursionExceptionForVariable', array($variable['name'] . '(' . $variable['type'] . ')')));
```
Comment (AltamashShaikh) [inline API/Import.php:149]: @tsteur Should we capture all such exceptions in a Array lets say and based on that throw an exception or 1 at a time is fine ?

Comment (tsteur) [reply API/Import.php:149]: not needed for now @AltamashShaikh
