### PR TITLE
started updating xdebug.max_nesting_level to 2500 if lower value set

### LINKED ISSUE #337: If xdebug is enabled then change limit to prevent self-referencing variable loop
As Operations Engineer, I had to debug a infinite loop happening in Matomo in all requests.

500 Internal Error , `Xdebug has detected a possible infinite loop, and aborted your script with a stack depth of '256' frames`

In the end I found the culprit to be  user defined variable in Tagmanager, that referenced itself. UserID variable had `{{UserID}}` in its user id field.

The `Enable Preview` function was just hanging.

Can this be prevented or mitigated by a better warning?

```
# ./matomo-console.sh tagmanager:regenerate-released-containers
ERROR [2021-07-30 17:03:13] 139  Uncaught exception: Error: Xdebug has detected a possible infinite loop, and aborted your script with a stack depth of '256' frames in /code/matomo/core/Container/StaticContainer.php:44
Stack trace:
#0 /code/matomo/core/Container/StaticContainer.php(44): end()
#1 /code/matomo/core/Container/StaticContainer.php(81): Piwik\Container\StaticContainer::getContainer()
#2 /code/matomo/core/Config.php(64): Piwik\Container\StaticContainer::get()
#3 /code/matomo/core/Db.php(815): Piwik\Config::getInstance()
#4 /code/matomo/core/Db.php(341): Piwik\Db::logSql()
#5 /code/matomo/core/Option.php(184): Piwik\Db::fetchOne()
#6 /code/matomo/core/Option.php(48): Piwik\Option->getValue()
#7 /code/matomo/core/Db/Schema/Mysql.php(599): Piwik\Option::get()
#8 /code/matomo/core/Db/Schema.php(157): Piwik\Db\Schema\Mysql->getInstallVersion()
#9 /code/matomo/core/DbHelper.php(123): Piwik\Db\Schema->getInstallVersion()
#10 /code/matomo/core/DbHelper.php(128): Piwik\DbHelper::getInstallVersion()
#11 /code/matomo/core/Tracker/TrackerCodeGenerator.php(237): Piwik\DbHelper::wasMatomoInstalledBeforeVersion()
#12 /code/matomo/core/Tracker/TrackerCodeGenerator.php(215): Piwik\Tracker\TrackerCodeGenerator->shouldPreferPiwikEndpoint()
#13 /code/matomo/plugins/TagManager/Template/Variable/MatomoConfigurationVariable.php(62): Piwik\Tracker\TrackerCodeGenerator->getJsTrackerEndpoint()
#14 /code/matomo/plugins/TagManager/Template/BaseTemplate.php(298): Piwik\Plugins\TagManager\Template\Variable\MatomoConfigurationVariable->getParameters()
#15 /code/matomo/plugins/TagManager/Model/Variable.php(360): Piwik\Plugins\TagManager\Template\BaseTemplate->toArray()
#16 /code/matomo/plugins/TagManager/Model/Variable.php(318): Piwik\Plugins\TagManager\Model\Variable->enrichVariable()
#17 /code/matomo/plugins/TagManager/Context/BaseContext.php(347): Piwik\Plugins\TagManager\Model\Variable->findVariableByName()
#18 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#19 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#20 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#21 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#22 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#23 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#24 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#25 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#26 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#27 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#28 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#29 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#30 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#31 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#32 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#33 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#34 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#35 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#36 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#37 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#38 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#39 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#40 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#41 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#42 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#43 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#44 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#45 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#46 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#47 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#48 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#49 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#50 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#51 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#52 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#53 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#54 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#55 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#56 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#57 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#58 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#59 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#60 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#61 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#62 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#63 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#64 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#65 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#66 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#67 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#68 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#69 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#70 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#71 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#72 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#73 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#74 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#75 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#76 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#77 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#78 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#79 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#80 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#81 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#82 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#83 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#84 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#85 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#86 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#87 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#88 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#89 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#90 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#91 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#92 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#93 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#94 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#95 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#96 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#97 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#98 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#99 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#100 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#101 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#102 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#103 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#104 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#105 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#106 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#107 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#108 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#109 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#110 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#111 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#112 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#113 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#114 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#115 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#116 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#117 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#118 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#119 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#120 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#121 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#122 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#123 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#124 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#125 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#126 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#127 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#128 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#129 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#130 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#131 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#132 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#133 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#134 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#135 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#136 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#137 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#138 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#139 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#140 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#141 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#142 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#143 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#144 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#145 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#146 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#147 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#148 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#149 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#150 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#151 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#152 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#153 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#154 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#155 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#156 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#157 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#158 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#159 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#160 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#161 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#162 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#163 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#164 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#165 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#166 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#167 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#168 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#169 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#170 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#171 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#172 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#173 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#174 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#175 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#176 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#177 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#178 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#179 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#180 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#181 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#182 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#183 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#184 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#185 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#186 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#187 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#188 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#189 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#190 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#191 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#192 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#193 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#194 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#195 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#196 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#197 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#198 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#199 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#200 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#201 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#202 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#203 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#204 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#205 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#206 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#207 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#208 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#209 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#210 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#211 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#212 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#213 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#214 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#215 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#216 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#217 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#218 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#219 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#220 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#221 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#222 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#223 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#224 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#225 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#226 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#227 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#228 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#229 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#230 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#231 /code/matomo/plugins/TagManager/Context/BaseContext.php(296): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#232 /code/matomo/plugins/TagManager/Context/BaseContext.php(222): Piwik\Plugins\TagManager\Context\BaseContext->parameterToVariableJs()
#233 /code/matomo/plugins/TagManager/Context/BaseContext.php(362): Piwik\Plugins\TagManager\Context\BaseContext->parametersToVariableJs()
#234 /code/matomo/plugins/TagManager/Context/BaseContext.php(153): Piwik\Plugins\TagManager\Context\BaseContext->variableToArray()
#235 /code/matomo/plugins/TagManager/Context/WebContext.php(112): Piwik\Plugins\TagManager\Context\BaseContext->generatePublicContainer()
#236 /code/matomo/plugins/TagManager/Model/Container.php(123): Piwik\Plugins\TagManager\Context\WebContext->generate()
#237 /code/matomo/plugins/TagManager/TagManager.php(276): Piwik\Plugins\TagManager\Model\Container->generateContainer()
#238 /code/matomo/core/Context.php(75): Piwik\Plugins\TagManager\TagManager->Piwik\Plugins\TagManager\{closure}()
#239 /code/matomo/plugins/TagManager/TagManager.php(277): Piwik\Context::changeIdSite()
#240 /code/matomo/core/Access.php(664): Piwik\Plugins\TagManager\TagManager->Piwik\Plugins\TagManager\{closure}()
#241 /code/matomo/plugins/TagManager/TagManager.php(287): Piwik\Access::doAsSuperUser()
#242 [internal function]: Piwik\Plugins\TagManager\TagManager->regenerateReleasedContainers()
#243 /code/matomo/core/EventDispatcher.php(141): call_user_func_array()
#244 /code/matomo/core/Piwik.php(809): Piwik\EventDispatcher->postEvent()
#245 /code/matomo/plugins/TagManager/Commands/RegenerateContainers.php(26): Piwik\Piwik::postEvent()
#246 /code/matomo/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(257): Piwik\Plugins\TagManager\Commands\RegenerateContainers->execute()
#247 /code/matomo/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Symfony\Component\Console\Command\Command->run()
#248 /code/matomo/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand()
#249 [internal function]: Symfony\Component\Console\Application->doRun()
#250 /code/matomo/core/Console.php(130): call_user_func()
#251 /code/matomo/core/Access.php(673): Piwik\Console->Piwik\{closure}()
#252 /code/matomo/core/Console.php(131): Piwik\Access::doAsSuperUser()
#253 /code/matomo/core/Console.php(82): Piwik\Console->doRunImpl()
#254 /code/matomo/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Piwik\Console->doRun()
#255 /code/matomo/console(32): Symfony\Component\Console\Application->run()
#256 {main}
Uncaught exception in /code/matomo/core/Container/StaticContainer.php line 44:
Xdebug has detected a possible infinite loop, and aborted your script with a stack depth of '256' frames

```

I found the problematic value by adding a line printing the variable name in [`plugins/TagManager/Context/BaseContext.php`](https://github.com/matomo-org/tag-manager/blob/4.x-dev/Context/BaseContext.php#L342)
and running `console tagmanager:regenerate-released-containers`

```php
    protected function variableToArray($container, $variableNameOrVariable)
    {
        if (is_array($variableNameOrVariable)) {
            $variable = $variableNameOrVariable;
        } else {
            print("debug: ".$variableNameOrVariable."\n"); # debug line added
            $variable = $this->variableModel->findVariableByName($container['idsite'], $container['idcontainerversion'], $variableNameOrVariable);
        }
        if ($variable) {
```

### PR DESCRIPTION
**Pull request by AltamashShaikh**
started updating xdebug.max_nesting_level to 2500 if lower value set
Fixes: #337 

### Description:

Please include a description of this change and which issue it fixes. If no issue exists yet please include context and what problem it solves.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

File: TagManager.php [hunk 1]
```diff
@@ -40,6 +40,17 @@ class TagManager extends \Piwik\Plugin
 {
     public static $enableAutoContainerCreation = true;
 
+    public function __construct($pluginName = false)
```
Comment (AltamashShaikh) [inline TagManager.php]: Tried using `postLoad()` but it didn't work for me

Comment (tsteur) [reply TagManager.php]: @AltamashShaikh can we move this into the `registerEvents` method maybe? That's because TagManager plugin might not be enabled and then we don't need to do this

Comment (AltamashShaikh) [reply TagManager.php]: Moved

**Review by tsteur — COMMENTED** [review]
Looks good to me @AltamashShaikh . Just realising another thought as mentioned in slack could be actually to move it to `API.php` in the constructor. Then we would change this value only when it's actually needed reducing possible side effects like hard to reproduce issues (imagine we get a bug report around max nested level in the future and we can't reproduce it because user has TagManager disabled but we have it enabled, just some random thought).

**Comment by AltamashShaikh** [comment]
> Looks good to me @AltamashShaikh . Just realising another thought as mentioned in slack could be actually to move it to `API.php` in the constructor. Then we would change this value only when it's actually needed reducing possible side effects like hard to reproduce issues (imagine we get a bug report around max nested level in the future and we can't reproduce it because user has TagManager disabled but we have it enabled, just some random thought).

@tsteur Agreed is better to have in `API.php`.
I have moved the code and it seems to work as expected

**Review by tsteur — APPROVED** [review]
looks good to merge if tests pass
